### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by uwap** [uwap/mqtt-control-map#11]
**Todo:**

- [x] Clean up the code for ui components (#1/#12)
- [x] Clean up other code pieces (#1/#12)
- [x] DRY (#1/#12)
- [x] Allow changing the icon (not just the color) depending on the current state (#12)
- [x] Also allow changing the icons in the sidebar depending on the current state
- [ ] Write more and better documentation (#2)
- [x] Clean up the build and deployment (webpack)
- [x] Add support for more than one space (#3)
- [ ] Add more things to the config utility (#7)
- [x] Fix all flow errors
- [ ] Add an example image to the readme
- [x] Maybe do some continous deployment things
